training.set=./dataset/douban-book/train.txt
test.set=./dataset/douban-book/test.txt
model.name=BSPM
model.type=graph
item.ranking=-topN 20
embedding.size=64
num.max.epoch=400
batch_size=2048
learnRate=0.001
reg.lambda=0.0001
BSPM=-sharpen_solver rk4 -sharpen_T 2 -sharpen_K 1 -idl_beta 0.500000
output.setup=-dir ./results/
